//! The *text* of the managed block (PRD §19.7): its markers, the per-lab
//! sections inside it, and the stanzas inside those.
//!
//! Everything here is a pure function over strings, because the thing it
//! produces lands in a file vmlab does not own. The writer in
//! [`super`] adds the locking, the atomic rename and the `ssh -G` check;
//! this half can be reasoned about — and tested — one string at a time.
//!
//! Three properties the shape exists to give:
//!
//! - **Deterministic ordering** (lab → machine → login label), so a
//!   dotfiles-tracked `~/.ssh/config` shows a diff only when something really
//!   changed.
//! - **The block is the record.** Each lab's stanzas carry that lab's
//!   canonical root in a machine-readable comment, which is what
//!   [`Managed::refresh`](super::Managed::refresh) reads to drop a lab that
//!   no longer exists. There is no bookkeeping file to fall out of step with
//!   the file that matters.
//! - **Nothing is repaired.** Mangled markers make [`split`] refuse, naming
//!   file and line; vmlab does not edit its way out of a file somebody else
//!   wrote.

use std::path::{Path, PathBuf};

use anyhow::{Result, bail};

use super::{Alias, LabBlock, Managed};

/// The line vmlab's region opens with. Matched exactly (after trimming), so a
/// developer who edits it gets a refusal rather than a second block.
pub const BEGIN: &str = "# BEGIN vmlab managed block";
/// The line it closes with.
pub const END: &str = "# END vmlab managed block";

/// The note under [`BEGIN`], for the person who finds this in their config.
const NOTE: &[&str] = &[
    "# Generated by `vmlab ssh-config`; every vmlab command that loads a lab",
    "# rewrites it. Edits between the markers are lost. Your own stanzas are",
    "# never moved — only this region is.",
];

/// What a lab's section header is spelled with. The lab's canonical root
/// follows on the same line, so pruning reads one line rather than parsing
/// ssh_config grammar.
const SECTION_LAB: &str = "# vmlab lab \"";
const SECTION_ROOT: &str = "\" root=";

/// A config file, cut into the region vmlab owns and everything else.
#[derive(Debug, Default)]
pub struct Split {
    /// Every line outside the markers, in the order the developer wrote
    /// them. Re-emitted below the block, never reordered.
    pub outside: Vec<String>,
    /// The lines between the markers; empty when the file has no block.
    pub inside: Vec<String>,
}

/// Cut `text` at vmlab's markers, or refuse.
///
/// The refusals are the point: one marker of a pair, a duplicated pair, or an
/// `END` before its `BEGIN` all mean the file is not in a state vmlab can
/// reason about, and the answer is an error naming file and line rather than
/// a repair attempt on somebody else's file.
pub fn split(text: &str, path: &Path) -> Result<Split> {
    let file = path.display();
    let mut begin: Option<usize> = None;
    let mut end: Option<usize> = None;

    for (i, line) in text.lines().enumerate() {
        let (line_no, trimmed) = (i + 1, line.trim());
        if trimmed == BEGIN {
            if begin.is_some() {
                bail!("{file}:{line_no}: a second vmlab block opens here{TAIL}");
            }
            begin = Some(i);
        } else if trimmed == END {
            if end.is_some() {
                bail!("{file}:{line_no}: a second vmlab block closes here{TAIL}");
            }
            if begin.is_none() {
                bail!("{file}:{line_no}: vmlab's block closes here but never opened{TAIL}");
            }
            end = Some(i);
        }
    }

    let lines = || text.lines().map(str::to_string);
    match (begin, end) {
        (None, None) => Ok(Split {
            outside: lines().collect(),
            inside: Vec::new(),
        }),
        (Some(b), Some(e)) => Ok(Split {
            outside: lines()
                .enumerate()
                .filter(|(i, _)| *i < b || *i > e)
                .map(|(_, l)| l)
                .collect(),
            inside: lines().skip(b + 1).take(e - b - 1).collect(),
        }),
        (Some(b), None) => {
            bail!(
                "{file}:{}: vmlab's block opens here and never closes{TAIL}",
                b + 1
            )
        }
        // An `END` with no `BEGIN` is refused where it is read, above.
        (None, Some(e)) => unreachable!("an END at line {} without a BEGIN", e + 1),
    }
}

/// The sentence every marker refusal ends with. vmlab does not own this file,
/// so the fix is the developer's.
const TAIL: &str = " — vmlab refuses to write a config whose markers it cannot \
                     read. Fix the markers (or delete the block) and run \
                     `vmlab ssh-config` again; nothing was changed.";

/// One lab's contribution to the block: its stanzas, tagged with the root
/// they were generated from.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Section {
    pub lab: String,
    /// The lab's canonical root. A root that no longer holds a `vmlab.wcl`
    /// is what makes this section stale.
    pub root: PathBuf,
    /// The stanzas as written. Kept **verbatim** for every lab but the one
    /// being refreshed: only that lab's file is in hand, and re-rendering a
    /// lab from memory vmlab does not have is how stanzas get invented.
    pub body: Vec<String>,
}

impl Section {
    /// Render one lab's stanzas from its declarations (§19.7): the machine's
    /// own alias, then one per non-default login label.
    pub fn of(block: &LabBlock, managed: &Managed) -> Self {
        // Sorted here rather than trusted from the caller: lab → machine →
        // login is a property of what lands on disk, and `Alias`'s own order
        // puts a machine's bare alias ahead of its labelled ones.
        let mut aliases = block.aliases.clone();
        aliases.sort();
        let mut body = Vec::new();
        for alias in &aliases {
            if !body.is_empty() {
                body.push(String::new());
            }
            body.extend(stanza(&block.lab, alias, managed));
        }
        Self {
            lab: block.lab.clone(),
            root: block.root.clone(),
            body,
        }
    }

    fn header(&self) -> String {
        format!(
            "{SECTION_LAB}{}{SECTION_ROOT}{}",
            self.lab,
            self.root.display()
        )
    }
}

/// One alias's stanza.
///
/// It sets no `HostName` — there is nothing to resolve, the `ProxyCommand`
/// *is* the connection — which also makes `%C` vary per alias, since the
/// alias is all that goes into it.
fn stanza(lab: &str, alias: &Alias, managed: &Managed) -> Vec<String> {
    let name = alias.name(lab);
    let mut out = vec![format!("Host {name}")];
    let mut set = |keyword: &str, value: String| out.push(format!("  {keyword} {value}"));

    set(
        "ProxyCommand",
        format!(
            "{} ssh-proxy {lab}/{}",
            shell_word(&managed.exe.display().to_string()),
            alias.machine
        ),
    );
    // The username is a *selector* over the machine's declared logins
    // (§19.2), so the labelled alias carries the label and the bare one
    // carries nothing — an `ssh` with no `-l` sends the local username, which
    // the facade reads as "I named nobody" and answers with the machine's
    // default login.
    if let Some(label) = &alias.login {
        set("User", config_word(label));
    }
    // vmlab's own `known_hosts`, beside the host keys it mints, so
    // `~/.ssh/known_hosts` is never touched (§19.3). `accept-new` because the
    // entry is written by the lab daemon as the facade comes up: a first
    // attach must not need a fingerprint prompt, while a *changed* key still
    // refuses.
    set(
        "UserKnownHostsFile",
        config_word(&managed.known_hosts.display().to_string()),
    );
    set("StrictHostKeyChecking", "accept-new".into());
    // Clients spawn several `ssh`/`scp` processes per session and each would
    // otherwise cost a handshake *and* a domain logon (§19.3). The socket
    // path is `%C` — OpenSSH's own token, 40 hex characters, **bounded by
    // construction** — under the runtime directory where vmlab's other
    // control sockets already live (§19.7's socket-path rule).
    set("ControlMaster", "auto".into());
    set(
        "ControlPath",
        config_word(&managed.control_dir.join("%C").display().to_string()),
    );
    set("ControlPersist", "10m".into());
    out
}

/// Render the whole block, sections sorted by lab then root.
///
/// Sorting rather than preserving encounter order is what makes a dotfiles
/// diff mean something: the same set of labs renders the same bytes, whichever
/// lab directory the developer happened to run a command in.
pub fn render(sections: &[Section]) -> String {
    let mut sorted: Vec<&Section> = sections.iter().collect();
    sorted.sort_by(|a, b| (&a.lab, &a.root).cmp(&(&b.lab, &b.root)));

    let mut out = vec![BEGIN.to_string()];
    out.extend(NOTE.iter().map(|l| l.to_string()));
    for section in sorted {
        out.push(String::new());
        out.push(section.header());
        out.extend(section.body.iter().cloned());
    }
    out.push(END.to_string());
    out.join("\n")
}

/// Read the sections back out of a block.
///
/// Anything before the first section header — vmlab's own note, blank lines —
/// is dropped, because [`render`] writes it back. A line vmlab does not
/// recognise inside a section stays with that section: it is inside the
/// markers, so it is vmlab's region, and the lab it belongs to is the one to
/// carry it until that lab is next refreshed.
pub fn sections(inside: &[String]) -> Vec<Section> {
    let mut out: Vec<Section> = Vec::new();
    for line in inside {
        match header(line) {
            Some((lab, root)) => out.push(Section {
                lab,
                root,
                body: Vec::new(),
            }),
            None => {
                if let Some(section) = out.last_mut() {
                    section.body.push(line.clone());
                }
            }
        }
    }
    for section in &mut out {
        while section.body.last().is_some_and(|l| l.trim().is_empty()) {
            section.body.pop();
        }
    }
    out
}

/// `# vmlab lab "<name>" root=<path>` → the name and the root.
fn header(line: &str) -> Option<(String, PathBuf)> {
    let rest = line.trim_start().strip_prefix(SECTION_LAB)?;
    let (lab, root) = rest.split_once(SECTION_ROOT)?;
    Some((lab.to_string(), PathBuf::from(root)))
}

/// A `Host` pattern (or any other config value) that beats vmlab's own
/// keyword, if the file itself holds one.
///
/// Only ever consulted after `ssh -G` has already said vmlab lost, and only
/// to *name* the winner: OpenSSH takes the first value it obtains for a
/// keyword, so with vmlab's region hoisted to the top the winner can only be
/// something above it — which means a displaced block, and this finds the
/// stanza that displaced it. `None` means the winner is outside this file
/// (an `Include`, `/etc/ssh/ssh_config`, the command line), which the caller
/// says instead.
pub fn culprit(text: &str, keyword: &str) -> Option<(String, String, usize)> {
    let mut pattern: Option<String> = None;
    for (i, line) in text.lines().enumerate() {
        let trimmed = line.trim();
        if trimmed == BEGIN {
            // Everything from here down is vmlab's own, and everything below
            // the block loses to it anyway.
            return None;
        }
        let Some((word, rest)) = trimmed.split_once(char::is_whitespace) else {
            continue;
        };
        if word.eq_ignore_ascii_case("host") || word.eq_ignore_ascii_case("match") {
            pattern = Some(format!("{word} {}", rest.trim()));
        } else if word.eq_ignore_ascii_case(keyword) {
            let scope = pattern
                .clone()
                .unwrap_or_else(|| "Host * (the file's own preamble)".to_string());
            return Some((scope, word.to_string(), i + 1));
        }
    }
    None
}

/// Quote a value for an ssh_config keyword if it needs it. OpenSSH's own
/// tokeniser reads `"…"` here, which is how a path with a space survives.
fn config_word(value: &str) -> String {
    match value.contains(|c: char| c.is_whitespace() || c == '"') {
        false => value.to_string(),
        true => format!("\"{}\"", value.replace('"', "\\\"")),
    }
}

/// Quote a word for the `/bin/sh` that runs a `ProxyCommand`. vmlab controls
/// exactly one word of that command line — the path to its own binary — and
/// a developer whose checkout lives under a directory with a space in it
/// should still get a working alias.
fn shell_word(value: &str) -> String {
    match value
        .chars()
        .all(|c| c.is_ascii_alphanumeric() || "._-/".contains(c))
    {
        true => value.to_string(),
        false => format!("'{}'", value.replace('\'', r"'\''")),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn managed() -> Managed {
        Managed::for_home(Path::new("/home/dev"))
    }

    fn section(lab: &str, root: &str, machines: &[(&str, &[&str])]) -> Section {
        Section::of(
            &LabBlock {
                lab: lab.to_string(),
                root: PathBuf::from(root),
                aliases: machines
                    .iter()
                    .flat_map(|(m, labels)| {
                        std::iter::once(Alias {
                            machine: m.to_string(),
                            login: None,
                        })
                        .chain(labels.iter().map(|l| Alias {
                            machine: m.to_string(),
                            login: Some(l.to_string()),
                        }))
                    })
                    .collect(),
                unaliasable: Vec::new(),
            },
            &managed(),
        )
    }

    /// The stanza is the whole contract with every client: the alias, the
    /// proxy, vmlab's own `known_hosts`, and a mux socket bounded by
    /// construction.
    #[test]
    fn a_stanza_carries_the_proxy_the_known_hosts_and_the_mux() {
        let body = section("probe", "/labs/probe", &[("dev01", &[])])
            .body
            .join("\n");
        assert!(body.starts_with("Host vmlab-probe-dev01\n"), "{body}");
        assert!(body.contains("ProxyCommand "), "{body}");
        assert!(body.contains(" ssh-proxy probe/dev01"), "{body}");
        assert!(body.contains("UserKnownHostsFile "), "{body}");
        assert!(body.contains("ControlMaster auto"), "{body}");
        assert!(
            body.contains("ControlPath ") && body.contains("/%C"),
            "{body}"
        );
        // The bare alias names no user: `ssh` sends the local username, which
        // the facade reads as "I named nobody" (§19.2).
        assert!(!body.contains("\n  User "), "{body}");
    }

    /// A non-default login is a *pick* in the editor's host list rather than
    /// something you have to know to type (§19.7).
    #[test]
    fn a_non_default_login_gets_its_own_alias() {
        let body = section("probe", "/labs/probe", &[("dev01", &["admin"])])
            .body
            .join("\n");
        assert!(body.contains("Host vmlab-probe-dev01-admin"), "{body}");
        assert!(body.contains("\n  User admin"), "{body}");
    }

    /// Same declarations in, same bytes out — whichever order the labs were
    /// visited in. That is what makes a dotfiles diff mean "something
    /// changed".
    #[test]
    fn rendering_is_deterministic_across_lab_order() {
        let a = section("alpha", "/labs/alpha", &[("web01", &[])]);
        let b = section("beta", "/labs/beta", &[("dev01", &["admin"])]);
        assert_eq!(render(&[a.clone(), b.clone()]), render(&[b, a]));
    }

    /// Machines sort under their lab, and labels under their machine — the
    /// lab → machine → login order §19.7 names.
    #[test]
    fn a_lab_renders_machine_then_login() {
        let rendered = render(&[section(
            "probe",
            "/labs/probe",
            &[("dev01", &["admin"]), ("web01", &[])],
        )]);
        let at = |needle: &str| rendered.find(needle).expect(needle);
        assert!(at("Host vmlab-probe-dev01\n") < at("Host vmlab-probe-dev01-admin"));
        assert!(at("Host vmlab-probe-dev01-admin") < at("Host vmlab-probe-web01"));
    }

    /// The block round-trips: what [`render`] writes, [`sections`] reads
    /// back — which is what lets one lab be refreshed without re-rendering
    /// every other lab from a file vmlab does not have.
    #[test]
    fn a_rendered_block_reads_back_as_its_sections() {
        let one = section("alpha", "/labs/alpha", &[("web01", &[])]);
        let two = section("beta", "/labs/beta", &[("dev01", &["admin"])]);
        let text = render(&[one.clone(), two.clone()]);
        let split = split(&text, Path::new("<test>")).unwrap();
        assert_eq!(sections(&split.inside), vec![one, two]);
    }

    /// A file with no block is all "outside", and nothing about it is
    /// rewritten.
    #[test]
    fn a_config_with_no_block_is_left_whole() {
        let text = "Host *\n  ForwardAgent yes\n";
        let split = split(text, Path::new("<test>")).unwrap();
        assert_eq!(split.outside, vec!["Host *", "  ForwardAgent yes"]);
        assert!(split.inside.is_empty());
    }

    /// Mangled markers refuse the write, naming file and line. Each of
    /// §19.7's three spellings, because each is a way to eat someone's file.
    #[test]
    fn mangled_markers_refuse_and_name_the_line() {
        let cases = [
            (format!("Host a\n{BEGIN}\nHost b\n"), "2:", "never closes"),
            (format!("Host a\n{END}\n"), "2:", "never opened"),
            (
                format!("{BEGIN}\n{END}\n{BEGIN}\n{END}\n"),
                "3:",
                "a second vmlab block opens",
            ),
            (
                format!("{BEGIN}\n{END}\n{END}\n"),
                "3:",
                "a second vmlab block closes",
            ),
        ];
        for (text, line, reason) in cases {
            let err = split(&text, Path::new("/home/dev/.ssh/config")).unwrap_err();
            let shown = format!("{err:#}");
            assert!(shown.contains("/home/dev/.ssh/config"), "{shown}");
            assert!(shown.contains(line), "{shown}");
            assert!(shown.contains(reason), "{shown}");
        }
    }

    /// When `ssh -G` says vmlab lost, the error has to name what beat it —
    /// which for a displaced block is a stanza in the same file.
    #[test]
    fn the_culprit_is_named_by_pattern_keyword_and_line() {
        let text = format!("Host *\n  ProxyCommand nc %h %p\n\n{BEGIN}\n{END}\n");
        let (pattern, keyword, line) = culprit(&text, "proxycommand").expect("a culprit");
        assert_eq!(pattern, "Host *");
        assert_eq!(keyword, "ProxyCommand");
        assert_eq!(line, 2);

        // Nothing above the block: the winner is outside this file, and the
        // caller says so rather than inventing a pattern.
        assert!(
            culprit(
                &format!("{BEGIN}\n{END}\nHost *\n  ProxyCommand x\n"),
                "proxycommand"
            )
            .is_none()
        );
    }

    /// A path with a space in it still produces a working stanza — the
    /// developer's checkout is not vmlab's to name.
    #[test]
    fn values_that_need_quoting_get_it() {
        assert_eq!(
            config_word("/home/a b/known_hosts"),
            "\"/home/a b/known_hosts\""
        );
        assert_eq!(config_word("/home/ab/known_hosts"), "/home/ab/known_hosts");
        assert_eq!(shell_word("/home/a b/vmlab"), "'/home/a b/vmlab'");
        assert_eq!(shell_word("/usr/bin/vmlab"), "/usr/bin/vmlab");
    }
}
