"""Every user-facing vmlab feature the end-to-end run accounts for.

A scenario reports each one as passed, failed or skipped with a reason.
Anything left unreported is a gap in the suite and fails the run.
"""

FEATURES: dict[str, str] = {
    # -- templates ---------------------------------------------------------
    "template.build.qcow2": "build a template from a cloud qcow2 source",
    "template.build.layered": "build a template layered on another (`source \"template\"`)",
    "template.list": "`vmlab template list`",
    "template.export": "`vmlab template export`",
    "template.import": "`vmlab template import`",
    "template.rm": "`vmlab template rm`",
    "template.clean": "`vmlab template clean` (dry run and apply)",
    "template.registry.login": "`vmlab template login` against a registry",
    "template.registry.push": "`vmlab template push` to an OCI registry",
    "template.registry.pull": "`vmlab template pull` from an OCI registry",
    "template.registry.search": "`vmlab template search --registry`",
    "template.registry.list-remote": "`vmlab template list --remote`",
    "template.registry.config": "`vmlab template registry add/list/remove`",
    "template.registry.lab-ref": "a lab VM referencing a registry template pulls it on `up`",
    "template.event": "the `template.built` event",
    # -- lab lifecycle -----------------------------------------------------
    "lab.validate": "`vmlab validate` accepts a good lab",
    "lab.validate.reject": "`vmlab validate` rejects a bad lab with a named error",
    "lab.up": "`vmlab up` brings the lab up",
    "lab.up.partial": "`vmlab up <machine>` brings up one machine",
    "lab.depends_on": "`depends_on` orders machine start",
    "lab.status": "`vmlab status` and `status -v`",
    "lab.down": "`vmlab down`",
    "lab.up.reload": "`vmlab up` after `down` runs the edited lab file; an edit over a running machine refuses",
    "lab.up.template-changed": "`vmlab up` refuses a VM whose template changed while its clone is kept",
    "lab.destroy": "`vmlab destroy`",
    "lab.pull": "`vmlab pull` fetches registry templates and images only",
    "lab.list": "`vmlab lab list`",
    "lab.info": "`vmlab lab info`",
    "lab.stop": "`vmlab lab stop`",
    "lab.down.release": "a full `vmlab down` releases the lab name, so another checkout declaring it can `up`",
    "lab.move": "`vmlab lab move` hands a stopped lab's clones to another checkout declaring its name, and refuses while it runs",
    "lab.status.conflict": "`vmlab status` (and `down`) in a checkout whose lab name is registered from another root exit 5 naming it",
    "lab.restart": "`vmlab lab restart` (and its refusal while running)",
    "lab.destroy.named": "`vmlab lab destroy <lab>`",
    "daemon.lifecycle": "`vmlab daemon start/status/stop`",
    # -- vm power and hardware ---------------------------------------------
    "vm.start": "`vmlab vm start`",
    "vm.stop": "`vmlab vm stop` and `--force`",
    "vm.restart": "`vmlab vm restart`",
    "vm.destroy": "`vmlab vm destroy`",
    "vm.ip": "`vmlab vm ip` and `--nic`",
    "vm.sleep": "a guest that suspends to RAM reports `suspended`, agent verbs refuse by name, `vm start` wakes it",
    "vm.prevent_sleep": "`prevent_sleep = true` wakes the guest the moment it suspends, recorded as `vm.woken`",
    "vm.hw.cpus-memory": "declared cpus and memory reach the guest",
    "vm.hw.disk": "an extra `disk` block with a size",
    "vm.hw.disk-from": "a `disk` built from a folder (FAT)",
    "vm.hw.cdrom": "a `cdrom` attachment",
    "vm.hw.floppy": "a `floppy` attachment",
    "vm.hw.tpm": "`tpm = true` (swtpm)",
    "vm.hw.firmware": "`firmware` selection (OVMF)",
    "vm.hw.secure_boot": "`secure_boot = true`",
    "vm.hw.qemu_args": "`qemu_args` passthrough",
    "vm.hw.nested": "`nested = true`",
    "vm.hw.gpu": "`gpu {}` passthrough / virgl",
    "vm.scratch": "a `template = \"scratch\"` VM",
    "vm.media.iso": "`media` built from a folder as an ISO",
    "vm.media.floppy": "`media` built from a folder as a floppy",
    # -- guest agent -------------------------------------------------------
    "agent.exec": "`vmlab exec` with exit code and output",
    "agent.exec.timeout": "`vmlab exec --timeout`",
    "agent.shell": "`vmlab shell` over the agent (pty)",
    "agent.cp.push": "`vmlab cp` host to guest",
    "agent.cp.pull": "`vmlab cp` guest to host",
    "agent.tail": "`vmlab tail`",
    "agent.osinfo": "`vmlab osinfo`",
    "agent.stats": "`vmlab machine stats`",
    "agent.capabilities": "`vmlab machine capabilities`",
    "agent.clipboard": "`vmlab clipboard set/get`",
    "agent.rehandshake": "an agent restarted inside the guest is handshaken again: status names the new one",
    "agent.update": "`vm start` refreshes a stale guest agent before reporting ready, marks the machine diverged, and status names the running agent",
    "agent.repair": "`vmlab machine repair-agent` and the diverged mark",
    "agent.eventlog": "`vmlab eventlog` (Windows event log)",
    # -- logins ------------------------------------------------------------
    "login.default": "`exec` runs as the declared default login",
    "login.user": "`exec --user <label>` and `--user root`",
    "login.password": "`exec --user --password` for an undeclared account",
    "login.elevated": "`elevated` Windows logins",
    # -- display and vision ------------------------------------------------
    "vision.screenshot": "`vmlab vm screenshot`",
    "vision.ocr": "`vmlab vm ocr` and `--region`",
    "vision.find-image": "`vmlab vm find-image`",
    "vision.sendkeys": "`vmlab vm sendkeys`",
    "vision.mouse": "`vmlab vm mouse-move/click/drag`",
    "console.tcp": "`vmlab console --tcp` serves VNC",
    "console.viewer": "`vmlab console` launching a GUI viewer, `gui = true`",
    # -- networking --------------------------------------------------------
    "net.dhcp": "DHCP leases on a segment",
    "net.static-ip": "a static `nic { ip }`",
    "net.dns.records": "DNS names for machines and `record` blocks",
    "net.dns.sinkhole": "`sinkhole` blocks",
    "net.dns.verb": "`vmlab dns`",
    "net.nat": "NAT egress from a segment",
    "net.nat.bulk": "a long NAT download keeps its throughput while the guest's receive window closes and reopens",
    "net.isolated": "`nic { isolated = true }`",
    "net.forward": "segment `forward` to a machine port",
    "net.forward.provisioned": "segment `forward` to a machine `up` provisions, installed and logged as `forward.installed`",
    "net.routes": "daemon routing between `routes_to` segments (source kept, rules applied, the rest isolated) and `route` blocks",
    "net.l3.block": "`block` rules",
    "net.l3.redirect": "`redirect` rules",
    "net.mtu": "segment `mtu`",
    "net.global": "`global = true` segments shared between labs",
    "net.peer": "cross-host `connect {}` trunks between supervisors",
    "net.fastpath": "`vmlab fastpath` reports the selected tier",
    "net.fastpath.kernel": "the afxdp / sockmap kernel tiers",
    # -- shares ------------------------------------------------------------
    "share.virtiofs": "`share` over virtiofs",
    "share.smb": "`share` over SMB",
    "share.readonly": "`share { readonly = true }`",
    "share.smb1": "SMB1 shares for legacy guests",
    "share.virtiofs.old-virtiofsd": "a virtiofs share on a virtiofsd without `--migration-mode` (Ubuntu 24.04's 1.10.0)",
    # -- containers --------------------------------------------------------
    "container.up": "an OCI container runs as a micro-VM",
    "container.idle": "`mode = :idle`",
    "container.env": "container `env`",
    "container.volume": "container `volume` (host path and named)",
    "container.port": "container `port` published on the host",
    "container.healthcheck": "container `healthcheck` and `container.unhealthy`",
    "container.exec": "`vmlab container exec`",
    "container.logs": "`vmlab container logs`",
    "container.shell": "`vmlab container shell` (pty)",
    "container.power": "`vmlab container start/stop/restart/ip/destroy`",
    # -- snapshots ---------------------------------------------------------
    "snapshot.vm.online": "online snapshot of a running VM, create and restore",
    "snapshot.vm.offline": "offline snapshot of a stopped VM",
    "snapshot.lab": "`vmlab snapshot create` for the whole lab",
    "snapshot.list-delete": "`vmlab snapshot list` and `delete`",
    "snapshot.container": "snapshots of a container",
    "snapshot.virtiofs.old-virtiofsd": "online snapshots refused, offline ones taken, on a virtiofsd too old to migrate",
    # -- scripting and events ----------------------------------------------
    "script.run": "`vmlab script` runs a wscript against the lab",
    "script.provision": "`provision` scripts run on `up`",
    "script.as_login": "wscript `as_login` / `as_account`",
    "script.segment-api": "wscript segment API (dns_set, block, forward, route_to/unroute_to)",
    "script.vision-api": "wscript screenshot / OCR / wait_for_text",
    "script.terminal": "wscript `terminal()` send / expect",
    "script.snapshot-api": "wscript snapshot / restore",
    "events.handlers": "`on` handlers fire for lab and machine events",
    "logs.streams": "`vmlab logs` events, serial, qemu and console streams",
    "logs.follow": "`vmlab logs -f`",
    # -- playbooks ---------------------------------------------------------
    "playbook.up": "a `playbook` block applied on `up`",
    "playbook.list": "`vmlab playbook list`",
    "playbook.check-apply": "`vmlab playbook check` and `apply`",
    # -- dev machines ------------------------------------------------------
    "dev.sync.host-to-guest": "workspace host edits reach the guest",
    "dev.sync.guest-to-host": "workspace guest edits reach the host",
    "dev.sync.modes": "executable bits travel both ways",
    "dev.sync.status-flush": "`vmlab dev sync status` and `flush`",
    "dev.sync.conflict": "a conflict halts, `dev sync diff` shows it, `resolve` clears it",
    "dev.select": "`dev sync` machine selection (argument, VMLAB_DEV_MACHINE)",
    "dev.snapshot-bracket": "snapshot capture flushes; restore re-seeds and `--discard-guest-changes`",
    # -- architectures -----------------------------------------------------
    "arch.emulated": "a non-x86 guest under TCG emulation",
}
